import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {Resvg} from '@resvg/resvg-js';
const root=path.dirname(fileURLToPath(import.meta.url));const out=path.join(root,'next/launch');fs.mkdirSync(out,{recursive:true});
const items=[
{id:'connected-city',title:'The city is connected.',lines:['THE CITY IS','CONNECTED.'],art:'city',status:'FEATURE SHOWCASE / STATUS BY SYSTEM',gate:'Use when the campaign destination is publicly available; replace [CAMPAIGN_URL] with that verified destination.',thread:['Every cut has a destination. Every object has a history. No one has the whole story. Meet the three systems behind Omertà’s connected city.','Explore the Hook / Market V2 candidate, World Graph Phase 1, and default-off Coordination API pilots. Implementation and public availability are different milestones.','Watch the films, trace a connection, and read the recorded local results: [CAMPAIGN_URL]'],discord:'The connected city showcase brings Omertà’s Hook, World Graph and Coordination Engine into one place. Watch the films, explore the browser simulations, or follow a real local API walkthrough. Each system has a clear built / next label. Explore: [CAMPAIGN_URL]',subject:'Meet Omertà’s connected city',email:'Every object and every piece of evidence can lead somewhere. Our feature showcase explains three connected Omertà systems through films, diagrams and interactive examples. Market V2 remains a candidate; World Graph Phase 1 is implemented; Coordination pilots default off. Start with the interactive field guide: [CAMPAIGN_URL]'},
{id:'world-graph',title:'The wreck is a beginning.',lines:['THE WRECK IS','A BEGINNING.'],art:'reserve',status:'PHASE 1 IMPLEMENTED / PHASE 2A IN DEVELOPMENT',gate:'Implementation showcase copy only. A public-play launch needs separate confirmation of availability and player eligibility.',thread:['The wreck is a beginning. Omertà’s implemented World Graph Phase 1 connects salvage, conserved materials and crafting.','Our local API example turns one wreck into materials, then consumes four scrap steel and 300 game cash to create one hardened steel. The example is synthetic; its handler responses are real.','Try the simulation and inspect the walkthrough: [CAMPAIGN_URL]. Phase 2A remains in development. NFT export is not live.'],discord:'Follow a wreck into the material ledger. The World Graph Phase 1 showcase demonstrates salvage and crafting through a local API example and a resettable browser simulation. Phase 1 is implemented and OMR-neutral; Phase 2A is in development and NFT export is not live. Trace the example: [CAMPAIGN_URL]',subject:'From wreck to material: inside World Graph',email:'A wreck can become the input to another object. Our World Graph showcase follows that transformation through the implemented Phase 1 handlers, with recorded inventory before and after crafting. Try the simulation, then read the exact response evidence: [CAMPAIGN_URL]. Phase 2A is still in development; NFT export is not live.'},
{id:'coordination',title:'No one has the whole story.',lines:['NO ONE HAS','THE WHOLE STORY.'],art:'turf',status:'VALUE-NEUTRAL API PILOTS / DEFAULT OFF',gate:'Review/demo announcement only. Do not call the pilots publicly live without explicit activation and scope verification.',thread:['No one has the whole story. Omertà’s Coordination Engine pilots connect original discoveries, deliberate sharing and corroborated conclusions.','In our local Split Ledger demonstration, two synthetic investigators discover the Docks and Foundry sources, share access, and complete one investigation. The pilot pays no reward.','Read the evidence and run the local example: [CAMPAIGN_URL]. Phases 00–01 are implemented for review; API pilots remain default off.'],discord:'Two original sources. One corroborated account. The Split Ledger case study follows two synthetic investigators through Omertà’s real local Coordination handlers. Deliberate sharing makes the missing source accessible. The pilots remain default off and value-neutral. Watch or reproduce the demonstration: [CAMPAIGN_URL]',subject:'Two sources, one conclusion: the Split Ledger',email:'The Split Ledger needs evidence one investigator cannot provide alone. Our new case study follows two original discoveries through sharing and completion using real local API handlers. It includes the recorded responses and a runnable fixture: [CAMPAIGN_URL]. This is an implementation demonstration of default-off, value-neutral pilots.'},
{id:'market-v2',title:'Every cut has a job.',lines:['EVERY CUT','HAS A JOB.'],art:'city',status:'MARKET V2 CANDIDATE / NOT DEPLOYED OR FUNDED',gate:'Candidate design announcement only. Deployment, funding and final parameters must be verified before writing a market-launch announcement.',thread:['Every cut has a job. Omertà’s Market V2 candidate defines a 9% base sell fee for the canonical pool: 2% developer, 1.6% RWA recipient, 2.4% community and 3% protocol liquidity.','Surge adds 0–1%; LP fees are additional. Companion mechanisms cover finite reserves, inventory bonds, solver-funded arbitrage, Turf fee rights and liquidity commitments.','Explore the allocation example: [CAMPAIGN_URL]. Market V2 is not deployed or funded. Independent pools have their own policies.'],discord:'Explore the Market V2 candidate’s fee flow with a browser-only allocation example. The canonical pool design has a 9% base sell fee across four destinations, plus bounded surge; LP fees are additional. Market V2 is not deployed or funded. Read the design showcase: [CAMPAIGN_URL]',subject:'Follow the fee: Omertà’s Market V2 candidate',email:'The Market V2 candidate gives the canonical pool’s base sell fee four explicit destinations. Our new interactive example makes the 9% allocation visible, alongside a 0–1% surge input. LP fees and other trading costs are outside the example. Explore: [CAMPAIGN_URL]. Market V2 remains a candidate, not deployed or funded.'}
];
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
for(const item of items){
 const copy=`# ${item.title}\n\nDRAFT — not sent or published.\nPublication gate: ${item.gate}\n\n## X thread\n${item.thread.map((t,i)=>`${i+1}. ${t}`).join('\n\n')}\n\n## Discord\n${item.discord}\n\n## Email\nSubject: ${item.subject}\n\n${item.email}\n\n## Graphic alt text\n${item.title} Conceptual noir artwork. Status: ${item.status}.\n`;
 fs.writeFileSync(path.join(out,item.id+'.md'),copy);
 const image=fs.readFileSync(path.join(root,'assets',item.art+'.jpg')).toString('base64');
 const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="900" viewBox="0 0 1600 900"><rect width="1600" height="900" fill="#101616"/><image href="data:image/jpeg;base64,${image}" x="1000" width="600" height="900" preserveAspectRatio="xMidYMid slice"/><rect x="1000" width="600" height="900" fill="#101616" opacity=".2"/><text x="80" y="100" font-family="Arial" font-size="26" fill="#c7af79" letter-spacing="7">OMERTÀ / THE CONNECTED CITY</text>${item.lines.map((t,i)=>`<text x="80" y="${330+i*112}" font-family="Arial" font-weight="700" font-size="${t.length>14?70:88}" fill="#eee8db">${esc(t)}</text>`).join('')}<line x1="80" x2="920" y1="670" y2="670" stroke="#53605b"/><text x="80" y="725" font-family="Arial" font-size="20" fill="#aacac0">${esc(item.status)}</text><text x="80" y="813" font-family="Arial" font-size="24" fill="#c7af79">OMERTA.FUN</text><text x="1040" y="855" font-family="Arial" font-size="13" fill="#eee8db">CONCEPTUAL ARTWORK / NOT GAMEPLAY FOOTAGE</text></svg>`;
 const render=new Resvg(svg,{font:{loadSystemFonts:true}});fs.writeFileSync(path.join(out,item.id+'.png'),render.render().asPng());fs.writeFileSync(path.join(out,item.id+'.svg'),svg);
}
fs.writeFileSync(path.join(out,'content.json'),JSON.stringify(items,null,2));
fs.writeFileSync(path.join(out,'index.html'),`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Omertà — launch announcement kit</title><link rel="stylesheet" href="../next.css"><main class="shell"><header class="mast"><a href="../index.html">← Collection</a><p class="eyebrow" style="margin-top:40px">OMERTÀ / ANNOUNCEMENT KIT</p><h1>Give each milestone<br>its own story.</h1><p class="lead">Four announcement sets. Each includes an X thread, Discord post, email draft, and matching graphic.</p><p class="status">Drafts only. Nothing has been sent or published.</p></header><p>Replace [CAMPAIGN_URL] with the verified public destination. Current wording announces a showcase or implementation milestone. It does not announce future systems as live.</p>${items.map(i=>`<section class="section"><p class="eyebrow">${i.status}</p><h2>${i.title}</h2><p class="source">Publication gate: ${i.gate}</p><img class="launch-art" src="${i.id}.png" alt="${esc(i.title+' Conceptual noir artwork. '+i.status)}"><div class="controls"><a class="action" href="${i.id}.md" download>Download channel copy ↓</a><a class="action" href="${i.id}.png" download>Download graphic ↓</a><a href="${i.id}.svg" download>SVG source</a></div><h3>X thread</h3><ol>${i.thread.map(t=>`<li>${esc(t)}</li>`).join('')}</ol><details><summary>Discord and email drafts</summary><h3>Discord</h3><p>${esc(i.discord)}</p><h3>Email / ${esc(i.subject)}</h3><p>${esc(i.email)}</p></details></section>`).join('')}<footer><a href="../index.html">Back to the collection</a><p>Artwork reused from the existing campaign. No new generation credits.</p></footer></main></html>`);
console.log('Four launch sets and four 1600×900 graphics built');
