import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));const out=path.join(root,'next');
const nav=`<nav class="subnav" aria-label="Collection"><a href="../index.html">Collection</a><a href="../demo/index.html">Try the demo</a><a href="../audience/index.html">Audience sheets</a><a href="../developer/index.html">Developer quickstart</a><a href="../launch/index.html">Launch kit</a><a href="../case-study/index.html">Case study</a></nav>`;
function page(folder,title,kicker,body,script=''){fs.mkdirSync(path.join(out,folder),{recursive:true});fs.writeFileSync(path.join(out,folder,'index.html'),`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} — Omertà</title><link rel="stylesheet" href="../next.css"></head><body><a class="skip" href="#main">Skip to content</a><main class="shell" id="main"><header class="mast">${nav}<p class="eyebrow">OMERTÀ / ${kicker}</p><h1>${title}</h1></header>${body}<footer><a href="../../index.html">The connected city</a><p>Local marketing collection · 14 September 2026 · Release status stated per system</p><a href="https://www.omerta.fun">Explore Omertà ↗</a></footer></main>${script}</body></html>`);}
page('demo','Trace the connection.','AN INTERACTIVE FIELD GUIDE',`<p class="lead">Move an amount through the fee design. Turn a wreck into material. Find the evidence one investigator is missing.</p><p class="status">Browser-only simulations. No wallet, account, transaction or live game state.</p><nav class="subnav" aria-label="Demo sections"><a href="#fees">01 / Follow the fee</a><a href="#workshop">02 / Work the material</a><a href="#evidence">03 / Share the source</a></nav>
<section class="section" id="fees"><p class="eyebrow">01 / MARKET V2 CANDIDATE</p><h2>Every cut has a job.</h2><div class="split"><div><p>Choose a notional amount to see the candidate canonical pool’s base sell fee split into four destinations.</p><form id="fee-form" novalidate><label class="field" for="amount">Example sell notional (illustrative units)<input type="number" id="amount" min="0.0001" max="1000000" step="any" value="1000" aria-describedby="fee-message"></label><label class="field" for="surge">Extra surge (%)<input type="number" id="surge" min="0" max="1" step="0.1" value="0" aria-describedby="fee-message"></label><button type="submit">Trace the allocation →</button></form><p class="feedback" id="fee-message" role="status"></p><p class="fine">9% base + 0–1% surge. LP fees are additional. These units do not quote an OMR price or expected trade proceeds. Rounding is display-only. Independent pools have their own policies.</p></div><div class="panel"><h3>The allocation ledger</h3><table class="ledger"><thead><tr><th>Destination</th><th>Units</th></tr></thead><tbody><tr><td>Developer · 2%</td><td id="dev"></td></tr><tr><td>RWA recipient · 1.6%</td><td id="rwa"></td></tr><tr><td>Community · 2.4%</td><td id="community"></td></tr><tr><td>Protocol liquidity · 3%</td><td id="pol"></td></tr><tr><td>Additional surge</td><td id="extra"></td></tr><tr><td>Total modeled fee</td><td id="total"></td></tr><tr><td>Remainder before other costs</td><td id="remainder"></td></tr></tbody></table><p class="status">Candidate. Market V2 is not deployed or funded.</p></div></div></section>
<section class="section" id="workshop"><p class="eyebrow">02 / WORLD GRAPH</p><h2>The wreck is a beginning.</h2><div class="split"><div><div class="diagram"><span><b>01</b>Consume wreck</span><span><b>02</b>Track materials</span><span><b>03</b>Craft steel</span></div><p>This example follows the inventory quantities from our real local API capture. Salvage consumes one wreck; crafting consumes declared inputs.</p><div class="controls"><button id="salvage">Salvage the wreck</button><button id="craft" disabled>Craft hardened steel</button><button class="secondary" id="reset-world">Reset workshop</button></div><p class="feedback" id="world-message" role="status"></p><p class="fine">This is an educational simulation of the captured recipe, not the entire eligibility system. Phase 1 is implemented and OMR-neutral. NFT export is not live.</p></div><div class="panel"><h3>Your example inventory</h3><table class="ledger"><thead><tr><th>Asset</th><th>Quantity</th></tr></thead><tbody>${[['wreck','Wreck'],['scrap','Scrap steel'],['wire','Wire'],['parts','Salvage parts'],['steel','Hardened steel'],['cash','Game cash']].map(([id,label])=>`<tr><td>${label}</td><td id="inv-${id}"></td></tr>`).join('')}</tbody></table></div></div></section>
<section class="section" id="evidence"><p class="eyebrow">03 / COORDINATION ENGINE</p><h2>No one has the whole story.</h2><div class="split"><div><p>Investigator A holds the Docks manifest. Investigator B can uncover the Foundry impression. A copy keeps its original source; sharing determines what A can use.</p><div class="controls"><button class="secondary" id="duplicate">Copy the Docks source</button><button id="discover">B discovers Foundry</button><button id="share" disabled>B shares with A</button><button class="secondary" id="revoke" disabled>Revoke Foundry access</button></div><p class="feedback" id="coord-message" role="status"></p><div class="controls"><button id="conclude" disabled>Record conclusion</button><button class="secondary" id="reset-coord">Reset investigation</button></div><p class="fine">Simplified source/access gate. Access revocation is demonstrated before completion; this simulation makes no claim about rewriting completed records. Default-off, value-neutral API pilots.</p></div><div class="panel"><h3>A’s accessible original sources</h3><p class="metric" id="independence"></p><p id="sources" style="overflow-wrap:anywhere"></p><p class="source">Two copies ≠ two independent sources.</p><a href="../case-study/index.html">See the actual captured result →</a></div></div></section><noscript><p>JavaScript is required for the simulations. Read the <a href="../case-study/index.html">case study</a> for the captured results.</p></noscript>`,`<script type="module" src="demo.js"></script>`);

const audiences=[
{id:'players',audience:'FOR PLAYERS',title:'Give every action a history.',lead:'Follow the connections between objects, materials and the people who know something you do not.',points:[['Make something from the wreck','The implemented World Graph Phase 1 connects car salvage to conserved materials and graph-defined crafting.'],['Bring the right people','Phase 1 includes a mystery and a four-account Crew operation. The separate Coordination pilots explore independent evidence and deliberate sharing.'],['Understand what is available','Try the browser simulation first. It changes no live inventory and makes each system’s release status explicit.']],status:'World Graph Phase 1 implemented. Phase 2A in development. Coordination pilots default off. NFT export not live.',cta:'Try the material and evidence demo',href:'../demo/index.html#workshop'},
{id:'developers',audience:'FOR AGENT DEVELOPERS',title:'Make your first connection.',lead:'Start with a reproducible local API example: recipes, inventory, original discoveries and a completed investigation.',points:[['Read what the server offers','Fetch recipe and graph catalogs. Use server-issued actions and content hashes instead of inventing transitions.'],['Handle state deliberately','The example uses idempotency keys, expected revisions and current sharing permissions. Two fixture accounts contribute separate origins.'],['Run a real local flow','The supplied script starts real repository handlers against an in-memory database, asserts results and closes. No production credentials required.']],status:'Coordination Phases 00–01 are default-off API pilots. The quickstart enables them only in its local process. It is not a hosted onboarding endpoint.',cta:'Run the developer quickstart',href:'../developer/index.html'},
{id:'partners',audience:'FOR ECOSYSTEM PARTNERS',title:'Find where your system fits.',lead:'Explore concrete integration boundaries across the game world, shared evidence and the proposed canonical market.',points:[['Objects and actions','World Graph Phase 1 supplies implemented material and crafting relationships. Discuss integrations against current APIs and explicit custody rules.'],['Evidence and collaboration','Coordination pilots demonstrate original discoveries and scoped sharing. Later delegation and economic adapters remain planned.'],['Capital and family interests','Market V2 proposes fixed fee destinations, finite reserves, inventory bonds, Turf fee rights and liquidity commitments. Treat these as candidate mechanisms.']],status:'Market V2 is not deployed or funded. No partnership, financial return, launch date or integration commitment is implied.',cta:'Review the facts and official links',href:'../../press-kit/index.html'}
];
fs.mkdirSync(path.join(out,'audience'),{recursive:true});fs.writeFileSync(path.join(out,'audience/content.json'),JSON.stringify(audiences,null,2));
for(const a of audiences){const content=`<div class="onepager"><p class="eyebrow">${a.audience}</p><p class="lead">${a.lead}</p>${a.points.map(([t,p])=>`<section class="section"><h2>${t}</h2><p>${p}</p></section>`).join('')}<p class="status">${a.status}</p><p><a class="action" href="${a.href}">${a.cta} →</a></p><p class="no-print"><a href="${a.id}.pdf" download>Download one-page PDF ↓</a></p></div>`;page('audience',a.title,a.audience,content);fs.renameSync(path.join(out,'audience/index.html'),path.join(out,`audience/${a.id}.html`));}
page('audience','Choose your entry point.','THREE AUDIENCES / THREE USEFUL NEXT STEPS',`<p class="lead">A concise introduction for the people exploring, building and collaborating with Omertà.</p><div class="download-list">${audiences.map(a=>`<a href="${a.id}.html">${a.audience} — ${a.title} →</a><a href="${a.id}.pdf" download>Download ${a.id} PDF ↓</a>`).join('')}</div>`);

page('developer','From request to result.','DEVELOPER QUICKSTART',`<p class="lead">Run real Omertà handlers with synthetic accounts. Salvage a wreck, craft hardened steel, then complete a shared investigation.</p><p class="status">Local repository example. In-memory database. No production token or wallet required.</p><section class="section"><h2>Watch the first three steps.</h2><video class="article-video" controls preload="none" poster="../../walkthrough/Inside-Omerta.png" aria-label="Narrated local API integration introduction"><source src="quickstart.mp4" type="video/mp4"><track kind="captions" src="quickstart.vtt" srclang="en" label="English"><a href="quickstart.mp4">Download the video</a></video><p class="fine">Reused narration and footage from our verified walkthrough. <a href="quickstart-transcript.txt">Read transcript</a> · <a href="../../walkthrough/index.html">Watch the complete investigation</a></p></section><section class="section reading"><h2>1. Run the fixture.</h2><p>Use an existing local Omertà checkout with its root dependencies installed and Node.js available. From the repository root:</p><pre><code>node brand/connected-city-materials/next/developer/run-demo.mjs</code></pre><p>The script rejects a configured DATABASE_URL or production NODE_ENV. It enables Coordination only within its process, creates three synthetic accounts in memory, calls the actual handlers, asserts outcomes and writes a local result file. It does not start a public server. Run it from a development shell without production configuration.</p><p><a href="run-demo.mjs" download>Download runnable example ↓</a></p></section><section class="section"><h2>2. Follow the material.</h2><div class="diagram"><span><b>READ</b>Recipe catalog</span><span><b>ACT</b>Salvage wreck</span><span><b>VERIFY</b>Read inventory</span><span><b>ACT</b>Craft steel</span></div><pre><code>GET  /v1/worldgraph/recipes
POST /v1/worldgraph/recipes/recipe:car_salvage_basic/salvage/{carId}
GET  /v1/worldgraph/inventory
POST /v1/worldgraph/recipes/recipe:hardened_steel/craft</code></pre><p>The observed salvage returns 6 scrap steel, 2 wire and 2 salvage parts. Crafting consumes 4 scrap steel and 300 game cash, creating 1 hardened steel.</p></section><section class="section reading"><h2>3. Follow the evidence.</h2><p>Read the Coordination catalog and use its current content hash to create the Split Ledger instance. Follow server-issued actions with the expected revision. Discover the Docks and Foundry sources under different accounts, resolve the sharing recipient, share, and read the instance again.</p><pre><code>GET  /v1/coordination
POST /v1/coordination/{graphId}/instances
     { expectedContentHash }
POST /v1/coordination/instances/{instanceId}/act
     { expectedRevision, actionId }
GET  /v1/coordination/knowledge
GET  /v1/coordination/knowledge/targets?characterName=Demo%20Archivist
POST /v1/coordination/knowledge/{claimId}/share
     { targetId, expectedAclRevision }</code></pre><p>POST requests use idempotency keys. Reuse a key only to retry the same logical operation with the same payload. The example generates a new key for each distinct operation. Do not hardcode action IDs or reuse stale revisions.</p><h3>Expected outcome</h3><pre><code>24 successful local responses
hardened steel: 1
remaining scrap steel: 2
game cash: 9700
Split Ledger: completed</code></pre><p>Success is evidence for this local fixture. Public rollout, account eligibility and other environments can differ.</p><h3>If something fails</h3><p>Missing package errors mean the root repository dependencies are not installed. The safety guard means the shell has production database configuration. Assertion failures mean the current checkout differs from the documented flow; inspect the failing response instead of weakening the assertions.</p><p><a href="example-results.json">View verified example results</a> · <a href="../case-study/index.html">Read the case study</a></p></section>`);

page('case-study','Two sources. One conclusion.','CASE STUDY / THE SPLIT LEDGER',`<p class="lead">How two synthetic investigators completed a shared investigation through Omertà’s real local API handlers.</p><p class="status">Implementation demonstration. No customer testimonial or production outcome is claimed.</p><section class="section reading"><h2>The problem</h2><p>Investigator A has a Docks manifest. Investigator B has a Foundry impression. A conclusion needs both original sources. Copying A’s evidence cannot manufacture a second origin.</p><div class="diagram"><span><b>INVESTIGATOR A</b>Docks manifest</span><span><b>INVESTIGATOR B</b>Foundry impression</span><span><b>SHARED RESULT</b>Corroborated ledger</span></div></section><section class="section"><h2>The observed sequence</h2><div class="split"><ol><li>Created separate local accounts and started the Split Ledger.</li><li>Each account followed server-issued actions to discover its source.</li><li>B resolved A as a sharing recipient and granted access.</li><li>A’s knowledge response contained both original sources.</li><li>A advanced the unlocked actions and received a completed instance.</li></ol><div class="panel"><p class="eyebrow">CAPTURED RESULT</p><pre><code>{
  "graphId": "omerta.coordination.split-ledger",
  "status": "completed",
  "revision": 5,
  "actions": []
}</code></pre><p class="source">Exact selected fields from the recorded final response.</p></div></div></section><section class="section reading"><h2>What the evidence supports</h2><p>The local flow demonstrates separate discovery, deliberate sharing and a successful corroborated conclusion. Across the wider capture, all 24 HTTP responses succeeded, including the World Graph salvage and crafting steps.</p><p>The source-independence rule is an implementation property described in the Coordination documentation. The captured happy path alone does not test every copy, revocation or permission boundary. The interactive exhibit illustrates those ideas; it is not additional production evidence.</p><p class="quote">“Two original discoverers, two surviving sources, one corroborated account. This record pays no reward.”</p><p class="source">Text returned by the local conclusion node; not a customer quotation.</p></section><section class="section reading"><h2>What remains outside this result</h2><p>Production adoption, public pilot activation, scalability, economic rewards and later delegation are outside this demonstration. The pilot remains default off and value-neutral. Synthetic accounts ran against pg-mem, with external RPC deliberately unavailable.</p><p>Capture date: 14 September 2026. Treat the evidence as a snapshot of the local checkout, not a release attestation.</p><div class="download-list"><a href="../../walkthrough/evidence.json" download>Download full captured responses ↓</a><a href="../developer/run-demo.mjs" download>Reproduce the local flow ↓</a><a href="../demo/index.html#evidence">Try the source-sharing simulation →</a><a href="../../walkthrough/index.html">Watch the narrated walkthrough →</a></div></section>`);

fs.writeFileSync(path.join(out,'index.html'),`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Omertà — Make the connection</title><link rel="stylesheet" href="next.css"><main class="shell"><header class="mast"><a href="../index.html">← The connected city</a><p class="eyebrow" style="margin-top:45px">OMERTÀ / THE NEXT CONNECTION</p><h1>Watch it.<br>Understand it.<br>Try it.</h1><p class="lead">Five ways to move from the story to the systems behind it.</p></header><section class="extras">${[['demo','01 / Interactive demo','Trace fees, materials and evidence'],['audience','02 / Audience one-pagers','Players, developers and partners'],['developer','03 / Developer quickstart','Runnable local example and narrated introduction'],['launch','04 / Launch announcement kit','Drafts and matching graphics'],['case-study','05 / Evidence-based case study','The Split Ledger, step by step']].map(([d,t,s])=>`<a href="${d}/index.html"><span>${t}</span><span>${s} →</span></a>`).join('')}</section><p class="fine">Reuses the existing campaign artwork and narration. No additional fal.ai generation was required.</p></main></html>`);
console.log('Interactive demo, audience pages, quickstart and case study built');
