// SPDX-License-Identifier: MIT
pragma solidity >=0.6.2 <0.9.0;

import {Test} from "forge-std/Test.sol";
import {console} from "forge-std/console.sol";
import {Handlers} from "./handlers/Handlers.sol";

/// @notice Contract to be used for quick testing with Foundry
contract FoundryTester is Test, Handlers {
    modifier asActor() override {
        vm.startPrank(actor);
        _;
        vm.stopPrank();
    }

    function setUp() public {
        setup();
    }

    // forge test --match-test test_sequence -vvv
    function test_sequence() public {
        // Add here call sequence to Handler's functions to reproduce failing property
    }

    function test_properties_at_setup() public {
        property_bank_supply_has_debt_or_reserve_backing();
        property_transmuter_ledger_is_physically_funded();
        property_actor_debt_is_within_reported_ltv();
        property_ltv_and_harvest_fee_are_compatible();
        property_staking_principal_sum_matches_global_total();
        property_staking_balance_covers_accounted_principal_and_pool();
        property_staking_apy_is_hard_capped();
        property_omr_tax_configuration_is_bounded();
        property_gear_live_supply_is_capped();
        property_twap_period_respects_floor();
    }

    function test_targeted_buffer_handler_rejects_the_first_unhealthy_supply_boundary() public {
        alchemist_deposit_clamped(type(uint256).max);
        uint256 supplyBefore = denari.totalSupply();
        uint256 debtBefore = alchemist.debtOf(actor);
        (bool success,) = address(this).call(abi.encodeCall(this.alchemist_mint_clamped, (uint256(1))));
        assertTrue(success, "the handler itself unexpectedly reverted");
        assertEq(denari.totalSupply(), supplyBefore, "the rejected boundary mint changed supply");
        assertEq(alchemist.debtOf(actor), debtBefore, "the rejected boundary mint changed debt");
        assertTrue(transmuter.bufferHealthy(), "the rejected boundary mint left an unhealthy buffer");
    }

    // ── Violation Repros (auto-generated by Step 11) ──────────────────
    // Each test_repro_* function below replays a shrunk fuzzer call
    // sequence that violated a property. Run all with:
    //   forge test --match-contract FoundryTester -vvv
}
