import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
if(process.env.DATABASE_URL || process.env.NODE_ENV==='production') throw new Error('This capture only permits a local in-memory database.');
process.env.COORDINATION_ENGINE='on';
process.env.COORDINATION_KNOWLEDGE='on';
process.env.COORDINATION_KNOWLEDGE_SHARING='on';
process.env.COORDINATION_ACCOUNT_IDS='demo-investigator-a,demo-investigator-b';
// Keep the real desk's unavailable-data state honest, with no external RPC calls.
process.env.DEFI_RPC_URL='http://127.0.0.1:1';
process.env.CHAIN_RPC_URL='http://127.0.0.1:1';
const {buildServer}=await import('../../../../src/server.js');
const app=await buildServer();
const here=path.dirname(fileURLToPath(import.meta.url));
const output=here;
const records=[];const tokens=new Map();
const fixture=async(id,name,loc)=>{
 await app.pool.query("INSERT INTO accounts(id,auth_provider,auth_subject) VALUES($1,'test',$1)",[id]);
 await app.pool.query('INSERT INTO account_persistent(account_id) VALUES($1)',[id]);
 await app.pool.query('INSERT INTO characters(id,account_id,name,loc,season,respect,cash) VALUES($1,$2,$3,$4,1,10000,10000)',[`${id}-character`,id,name,loc]);
 tokens.set(id,app.jwt.sign({sub:id,tv:0}));
};
const request=async(title,method,url,account,payload,key=crypto.randomUUID())=>{
 const r=await app.inject({method,url,...(payload===undefined?{}:{payload}),headers:{...(account?{authorization:`Bearer ${tokens.get(account)}`} :{}),...(method==='POST'?{'idempotency-key':key}:{})}});
 assert.equal(r.statusCode,200,`${title}: ${r.statusCode} ${r.body}`);
 const body=r.json();records.push({title,method,url,status:r.statusCode,...(payload===undefined?{}:{requestBody:payload}),body});return body;
};
await fixture('demo-mechanic','Demo Mechanic','foundry');
await fixture('demo-investigator-a','Demo Archivist','docks');
await fixture('demo-investigator-b','Demo Printer','foundry');
const carId=crypto.randomUUID();
await app.pool.query("INSERT INTO cars(id,character_id,model_id,trim_id,dmg,listed,pledged,minted_onchain,race_limit,pink_slip) VALUES($1,$2,'junker','stock',80,false,false,false,null,false)",[carId,'demo-mechanic-character']);
await request('Recipe catalog','GET','/v1/worldgraph/recipes','demo-mechanic');
await request('Before salvage','GET','/v1/worldgraph/inventory','demo-mechanic');
await request('Salvage a wreck','POST',`/v1/worldgraph/recipes/recipe:car_salvage_basic/salvage/${carId}`,'demo-mechanic');
await request('Materials after salvage','GET','/v1/worldgraph/inventory','demo-mechanic');
await request('Craft hardened steel','POST','/v1/worldgraph/recipes/recipe:hardened_steel/craft','demo-mechanic');
await request('Inventory after crafting','GET','/v1/worldgraph/inventory','demo-mechanic');
const catalog=await request('Coordination catalog','GET','/v1/coordination','demo-investigator-a');
const graph=catalog.graphs.find(g=>g.id==='omerta.coordination.split-ledger');assert(graph);
const start=async account=>(await request(`Start ${account.endsWith('a')?'Docks':'Foundry'} investigation`,'POST',`/v1/coordination/${graph.id}/instances`,account,{expectedContentHash:graph.contentHash})).instance;
const advance=async(account,instance,action=instance.actions[0])=>{
 assert(action,'Expected a server-issued action');
 return (await request('Advance investigation','POST',`/v1/coordination/instances/${instance.id}/act`,account,{expectedRevision:instance.revision,actionId:action.id})).instance;
};
const a='demo-investigator-a',b='demo-investigator-b';
let av=await start(a),bv=await start(b);
av=await advance(a,av);bv=await advance(b,bv);
av=await advance(a,av);bv=await advance(b,bv);
av=await advance(a,av,av.actions.find(x=>x.nodeId==='docks-source'));
bv=await advance(b,bv,bv.actions.find(x=>x.nodeId==='foundry-source'));
const ak=await request('Docks original evidence','GET','/v1/coordination/knowledge',a);
const bk=await request('Foundry original evidence','GET','/v1/coordination/knowledge',b);
const targets=await request('Choose a sharing recipient','GET','/v1/coordination/knowledge/targets?characterName=Demo%20Archivist',b);
const target=targets.targets.find(t=>t.kind==='account');assert(target);
await request('Share the Foundry source','POST',`/v1/coordination/knowledge/${bk.claims[0].id}/share`,b,{targetId:target.id,expectedAclRevision:bk.claims[0].aclRevision});
await request('Both sources visible','GET','/v1/coordination/knowledge',a);
av=await request('Evidence unlocks the gate','GET',`/v1/coordination/instances/${av.id}`,a);
for(let i=0;i<6&&av.actions?.length;i++) av=await advance(a,av);
await request('Investigation result','GET',`/v1/coordination/instances/${av.id}`,a);
const inventory=records.find(r=>r.title==='Inventory after crafting').body;
assert.equal(inventory.stacks.find(s=>s.templateId==='mat:hardened_steel').qty,1);
assert.equal(inventory.stacks.find(s=>s.templateId==='mat:scrap_steel').qty,2);
const cash=await app.pool.query('SELECT cash FROM characters WHERE id=$1',['demo-mechanic-character']);
assert.equal(Number(cash.rows[0].cash),9700);
assert.equal(records.at(-1).body.status,'completed');
fs.writeFileSync(path.join(output,'example-results.json'),JSON.stringify({capturedAt:new Date().toISOString(),environment:'Actual repository handlers; pg-mem; synthetic accounts; no production or external RPC',records},null,2));
console.log('PASS: 24 successful local responses; 1 hardened steel; 2 scrap steel; 9700 game cash; Split Ledger completed.');
await app.close();
