import {allocate,workshop,evidenceGate} from './model.js';
const $=id=>document.getElementById(id);const n=v=>v.toLocaleString('en-US',{maximumFractionDigits:4});
function fee(){try{const result=allocate($('amount').valueAsNumber,$('surge').valueAsNumber);['dev','rwa','community','pol'].forEach((id,i)=>$(id).textContent=n(result.portions[i]));$('extra').textContent=n(result.extra);$('total').textContent=n(result.total);$('remainder').textContent=n(result.remainder);$('fee-message').textContent='Allocation updated. Illustrative notional units; excludes LP fees, slippage and price impact.';$('fee-message').classList.remove('error');}catch(e){for(const id of ['dev','rwa','community','pol','extra','total','remainder'])$(id).textContent='—';$('fee-message').textContent=e.message;$('fee-message').classList.add('error');}}
$('fee-form').addEventListener('submit',e=>{e.preventDefault();fee();});fee();
let shop=workshop();function inventory(message){const s=shop.read();for(const key of Object.keys(s))$(`inv-${key}`).textContent=n(s[key]);$('craft').disabled=s.scrap<4||s.cash<300;$('salvage').disabled=!s.wreck;$('world-message').textContent=message;}
$('salvage').addEventListener('click',()=>{shop.salvage();inventory('Wreck consumed once. Added 6 scrap steel, 2 wire and 2 salvage parts. Crafting is now available.');});
$('craft').addEventListener('click',()=>{shop.craft();inventory('Created 1 hardened steel. Consumed 4 scrap steel and 300 game cash. Two scrap remain, so another craft is unavailable.');});
$('reset-world').addEventListener('click',()=>{shop=workshop();inventory('Reset: one wreck, no materials. Salvage the wreck to obtain crafting inputs.');});inventory('Start with one wreck. Crafting needs 4 scrap steel and 300 game cash.');
let foundry=false,shared=false,duplicate=false;function gate(message){const s=evidenceGate(foundry,shared,duplicate);$('sources').textContent=s.visible.join(' + ');$('independence').textContent=`${s.independent} / 2`;$('conclude').disabled=!s.ready;$('discover').disabled=foundry;$('share').disabled=!foundry||shared;$('revoke').disabled=!shared;$('duplicate').disabled=duplicate;$('coord-message').textContent=message;}
$('duplicate').addEventListener('click',()=>{duplicate=true;gate('Another copy of the Docks manifest still has one original source. The gate remains locked until Foundry evidence is shared.');});
$('discover').addEventListener('click',()=>{foundry=true;gate('Investigator B discovered the Foundry impression. A cannot use it until B shares access.');});
$('share').addEventListener('click',()=>{shared=true;gate('Investigator A can now access two distinct original sources. The conclusion is available.');});
$('revoke').addEventListener('click',()=>{shared=false;gate('Foundry access revoked. A current-access check locks the gate again before completion.');});
$('conclude').addEventListener('click',()=>{gate('Simulated conclusion complete: two original discoverers and two surviving sources. No reward is paid. Reset to explore another path.');for(const id of ['duplicate','discover','share','revoke','conclude'])$(id).disabled=true;});
$('reset-coord').addEventListener('click',()=>{foundry=false;shared=false;duplicate=false;gate('Reset: A has only the Docks manifest. Two distinct original sources are required.');});gate('A has the Docks manifest. Try a copy, or ask B to discover and share the Foundry source.');
