export function receipt(amount,surge){if(!Number.isFinite(amount)||amount<=0||amount>1000000||!Number.isFinite(surge)||surge<0||surge>1)throw new Error('Use an amount above 0 and up to 1,000,000, and surge between 0 and 1%.');return {developer:amount*.02,rwa:amount*.016,community:amount*.024,core:amount*.03,warChest:amount*surge/100};}
export const scenarios={
 healthy:{label:'Qualifying downside observation',idle:60,perAction:20,episode:50,lifetime:80,gate:null,explain:'Assume stress has been established, the observation is fresh, the downside range is eligible, spot and liquidity checks pass, no position is active, and cooldown has elapsed.'},
 selling:{label:'Heavy selling, finite inventory',idle:12,perAction:20,episode:50,lifetime:80,gate:null,explain:'Even when the downside regime qualifies, idle inventory can limit the budget. Selling pressure does not create funds. The 0–1% surge cap is separate from this deployment model.'},
 empty:{label:'Inventory depleted',idle:0,perAction:20,episode:50,lifetime:80,gate:null,explain:'Starting idle inventory is zero. Added funding can remove that constraint, but a higher price or a displayed range cannot replenish assets.'},
 cooldown:{label:'Cooldown has not elapsed',idle:60,perAction:20,episode:50,lifetime:80,gate:'Cooldown blocks a new placement.',explain:'Available money is not sufficient authority to deploy. A new eligible epoch and the configured minimum delay are also required.'},
 thin:{label:'Current liquidity check fails',idle:60,perAction:20,episode:50,lifetime:80,gate:'The market observation/current-liquidity checks do not qualify.',explain:'Historical pool measurements do not guarantee executable depth. This scenario assumes the relevant liquidity gate fails.'},
 exhausted:{label:'Lifetime deployment exhausted',idle:60,perAction:20,episode:50,lifetime:0,gate:null,explain:'Lifetime limits remain consumed. Adding inventory cannot restore them.'},
 paused:{label:'Controller deployment paused',idle:60,perAction:20,episode:50,lifetime:80,gate:'Safe pause blocks controller deployment.',explain:'This is a controller pause. The canonical Hook has no discretionary trading pause. Mature commitment exits and vested bond claims have independent paths.'}
};
export function deploymentBudget(s,additionalFunding=0){if(!Number.isFinite(additionalFunding)||additionalFunding<0)throw new Error('Funding must be nonnegative.');return s.gate?0:Math.min(s.idle+additionalFunding,s.perAction,s.episode,s.lifetime);}
export function independentEvidence(a,b,shared){const differentAccounts=a!==b;return {differentAccounts,ready:differentAccounts&&shared,reason:!differentAccounts?'Two origins held by one account do not satisfy this pilot’s account-independence requirement.':!shared?'Two accounts discovered the sources, but A has no current access to B’s evidence.':'Two original sources, two distinct accounts, and current access satisfy the simplified evidence gate.'};}
