// THE BLACK BOOK + THE CALL (STREET LIFE, task #318 — founder-directed).
//
// Phone numbers are DISCOVERABLE, never free: a MEETING (any completed two-party action — the one
// hook in withTwoCharacters) hands both sides the other's number; INTEL (a wiretap or dossier)
// earns it one-way; a CALLER reveals their own number to whoever they ring. ACCOUNT-keyed both
// sides (the dm_blocks posture): a number follows the bloodline, so the book survives death by
// construction and the heir keeps every line.
//
// THE CALL: contacts you've met ring you with requests (the founder's "as you rack up players or
// NPCs met they can give you quests"). Generated by the worker from your NPC contacts, paid from
// THE CONTACT'S OWN CASH (the population recycle-only rule — a request never conjures value at the
// point of fulfilment; both legs are character_id'd ledger rows, so §10.4 check (a) reconciles a
// pure transfer). Zero new faucet.
import crypto from 'node:crypto';
import { GameError, notify } from './game.js';
import { CONTACTS, GOODS, DISTRICTS, goodPriceOf, levelOf, contactRankOf, contactNextRank, contactStandingOf, jailed, districtName } from './rules.js';

const uid = () => crypto.randomUUID();

// Best-effort SAVEPOINT guard — attempted PER CALL, never cached module-wide (AUDIT-street-life
// F2). This helper rides BOTH contexts: inside a transaction (withTwoCharacters, the wire) and on
// a bare pool connection (sendDm — autocommit). Real Postgres refuses SAVEPOINT in autocommit
// (25P01), so a probe-once cache set by whichever context happened to run first poisons the other:
// in-txn-first meant every sendDm 'called' grant silently vanished into the outer catch. A context
// that refuses the savepoint falls back to the bare insert, which is safe exactly there —
// autocommit can't be txn-poisoned, and pg-mem (which can't parse SAVEPOINT at all) doesn't poison
// transactions on an errored statement. A failed book write must never roll back the action it
// rides in.
export async function recordContact(client, ownerAccount, contactAccount, how) {
  if (!ownerAccount || !contactAccount || ownerAccount === contactAccount) return;
  const insert = () => client.query(
    'INSERT INTO contacts (owner_account, contact_account, how) VALUES ($1,$2,$3) ON CONFLICT DO NOTHING',
    [ownerAccount, contactAccount, how]);
  try {
    let sp = true;
    try { await client.query('SAVEPOINT ct_ev'); } catch { sp = false; }
    if (!sp) { await insert(); return; }
    try { await insert(); await client.query('RELEASE SAVEPOINT ct_ev'); }
    catch { await client.query('ROLLBACK TO SAVEPOINT ct_ev').catch(() => {}); }
  } catch { /* the book never blocks the street */ }
}

// A MEETING is mutual — both walk away with the other's number.
export async function recordMeeting(client, aAccount, bAccount) {
  await recordContact(client, aAccount, bAccount, 'met');
  await recordContact(client, bAccount, aAccount, 'met');
}

export async function hasContact(q, ownerAccount, contactAccount) {
  return (await q.query('SELECT 1 FROM contacts WHERE owner_account=$1 AND contact_account=$2 LIMIT 1',
    [ownerAccount, contactAccount])).rows.length > 0;
}

// The book: every line you hold, resolved to the bloodline's CURRENT living street (the
// rivalsBoard pattern — JOIN, never ANY-of-array; account UUIDs NEVER leave the server, the
// client keys every action on the living characterId). A line with no living street is kept
// (the number outlives the man — the heir answers), shown dead until the heir rises.
export async function contactsBoard(pool, accountId) {
  const rows = (await pool.query(
    `SELECT ct.contact_account, ct.how, ct.met_at, ct.jobs,
            c.id AS char_id, c.name, c.respect, c.loc, c.is_npc
       FROM contacts ct
       LEFT JOIN characters c ON c.account_id = ct.contact_account AND c.alive
      WHERE ct.owner_account=$1 ORDER BY ct.met_at DESC LIMIT 200`, [accountId])).rows;
  // the ladder is counted, not stored — LIMIT 200 above is a display cap, so ask for the real total
  const lines = Number((await pool.query(
    'SELECT COUNT(*) n FROM contacts WHERE owner_account=$1', [accountId])).rows[0].n);
  const call = (await pool.query(
    `SELECT cc.*, n.name AS npc_name FROM contact_calls cc
       JOIN characters me ON me.account_id=$1 AND me.alive AND me.id = cc.character_id
       LEFT JOIN characters n ON n.id = cc.npc_character AND n.alive
      WHERE cc.expires_at > now()`, [accountId])).rows[0] || null;
  const next = contactNextRank(lines);
  return {
    lines, rank: contactRankOf(lines),
    nextRank: next ? { title: next.title, at: next.at, need: next.at - lines } : null,
    contacts: rows.map((r) => ({
      how: r.how, metAt: r.met_at,
      jobs: Number(r.jobs || 0), standing: contactStandingOf(r.jobs).name,
      street: r.char_id ? { id: r.char_id, name: r.name, level: levelOf(Number(r.respect)), loc: r.loc, npc: !!r.is_npc } : null,
    })),
    call: call && call.npc_name ? {
      from: call.npc_name, kind: call.kind, good: call.good_id, qty: call.qty ? Number(call.qty) : null,
      district: call.district, pay: Number(call.pay),
      expiresSeconds: Math.max(0, Math.ceil((new Date(call.expires_at) - Date.now()) / 1000)),
    } : null,
  };
}

// THE BOOK — who knows the most people. Pure status on a COUNT, so there is nothing to spend and
// nothing to drift; agents and residents are excluded like every other human board. Two flat
// queries + a JS join (the /v1/gangs precedent — pg-mem can't take the correlated form).
export async function contactsLeaderboard(pool, limit = 25) {
  const counts = (await pool.query(
    `SELECT ct.owner_account, COUNT(*)::int n FROM contacts ct
       JOIN account_persistent ap ON ap.account_id = ct.owner_account AND NOT ap.agent_flag AND NOT ap.npc_flag
      GROUP BY ct.owner_account`)).rows;
  if (!counts.length) return { book: [] };
  const streets = new Map((await pool.query(
    'SELECT account_id, id, name FROM characters WHERE alive AND NOT is_npc')).rows.map((r) => [r.account_id, r]));
  return {
    book: counts
      .map((c) => ({ lines: Number(c.n), street: streets.get(c.owner_account) }))
      .filter((x) => x.street)
      .sort((a, b) => b.lines - a.lines || String(a.street.id).localeCompare(String(b.street.id)))
      .slice(0, limit)
      .map((x, i) => ({ rank: i + 1, name: x.street.name, characterId: x.street.id,
        lines: x.lines, title: contactRankOf(x.lines) })),
  };
}

// ── THE CALL — worker generation. Bounded: at most GEN_PER_TICK placed per tick, ONE open call
// per street (the PK), and every request is affordable from the NPC's OWN pocket (skip if not —
// generation never writes value, fulfilment is the transfer). opts pin the picks for tests. ──
export async function generateContactCalls(pool, opts = {}) {
  const out = { placed: 0 };
  // two flat queries + a JS filter (pg-mem can't parse a correlated NOT EXISTS — the /v1/gangs precedent)
  const busy = new Set((await pool.query(
    'SELECT character_id FROM contact_calls WHERE expires_at > now()')).rows.map((r) => r.character_id));
  const candidates = (opts.characterId
    ? (await pool.query('SELECT id, account_id FROM characters WHERE id=$1 AND alive', [opts.characterId])).rows
    : (await pool.query(
        `SELECT DISTINCT c.id, c.account_id FROM characters c
           JOIN contacts ct ON ct.owner_account = c.account_id
           JOIN characters n ON n.account_id = ct.contact_account AND n.alive AND n.is_npc
          WHERE c.alive AND NOT c.is_npc LIMIT 50`)).rows
  ).filter((r) => !busy.has(r.id));
  const picked = candidates.map((r) => ({ r, k: Math.random() })).sort((a, b) => a.k - b.k)
    .slice(0, CONTACTS.GEN_PER_TICK).map((x) => x.r);
  for (const ch of picked) {
    try {
      const npcs = (await pool.query(
        `SELECT n.id, n.name, n.cash, n.loc, ct.jobs FROM contacts ct
           JOIN characters n ON n.account_id = ct.contact_account AND n.alive AND n.is_npc
          WHERE ct.owner_account=$1 ORDER BY n.id`, [ch.account_id])).rows;
      if (!npcs.length) continue;
      const npc = opts.npcCharacterId ? npcs.find((n) => n.id === opts.npcCharacterId) : npcs[Math.floor(Math.random() * npcs.length)];
      if (!npc) continue;
      // STANDING (step two): how they treat you scales with how many of their jobs you've finished.
      // It moves the ASK, never the source — a bigger request is still paid from this NPC's own
      // pocket and still skipped when they can't cover it, so the recycle-only rule is untouched.
      const st = contactStandingOf(npc.jobs);
      let kind = opts.kind || (Math.random() < 0.6 ? 'freight' : 'visit');
      let good = null, qty = null, pay = 0;
      if (kind === 'freight') {
        good = GOODS[Math.floor(Math.random() * GOODS.length)];
        qty = 1 + Math.floor(Math.random() * CONTACTS.CALL_FREIGHT_MAX_QTY);
        if (opts.goodId) { good = GOODS.find((g) => g.id === opts.goodId) || good; }
        if (opts.qty) qty = opts.qty;
        // a regular gets asked for more — the cap still bounds one request's size
        qty = Math.max(1, Math.min(CONTACTS.CALL_FREIGHT_MAX_QTY, Math.round(qty * st.qtyMult)));
        pay = Math.floor(qty * goodPriceOf(good.id, npc.loc) * CONTACTS.CALL_FREIGHT_PREMIUM_BPS / 10000);
        if (Number(npc.cash) < pay) kind = 'visit'; // they can't cover the freight — just ask you around
      }
      // (Lens C LOW-2) the tip is FIXED for a given standing, never min(tip, pocket): a sub-tip pay
      // would encode the NPC's exact pocket cash on the board + the notify. A contact who can't
      // cover it simply doesn't call (fulfilment still re-clamps to their live pocket — the void).
      if (kind === 'visit') {
        good = null; qty = null;
        const tip = Math.floor(CONTACTS.VISIT_TIP * st.tipMult);
        pay = Number(npc.cash) >= tip ? tip : 0;
      }
      if (pay <= 0) continue; // a broke contact asks for nothing
      const ins = await pool.query(
        `INSERT INTO contact_calls (character_id, npc_character, kind, good_id, qty, district, pay, expires_at)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT DO NOTHING`,
        [ch.id, npc.id, kind, good?.id || null, qty, npc.loc, pay, new Date(Date.now() + CONTACTS.CALL_TTL_MS)]);
      if (!ins.rowCount) continue;
      await notify(pool, ch.id, 'contact_call', {
        from: npc.name, kind, good: good?.id, qty, district: npc.loc, pay,
      }).catch(() => {});
      out.placed++;
    } catch (e) { console.error('[contacts] call generation failed', ch.id, e.message); }
  }
  return out;
}

// ── fulfil the open call — a TWO-PARTY action (withTwoCharacters on the NPC, so both rows are
// locked in sorted order: the payment can't clobber a concurrent residentAct, and the lock order
// matches every other PvP pair). The pay is a pure ledgered TRANSFER from the contact's pocket
// (`contact:freight` / `contact:visit`, both character_id'd with counterparty — §10.4 exact). ──
export async function fulfillCall(ch, npc, client, h) {
  if (jailed(ch)) throw new GameError('jailed', 'No errands from lockup.');
  const call = (await client.query(
    'SELECT * FROM contact_calls WHERE character_id=$1 FOR UPDATE', [ch.id])).rows[0];
  if (!call || new Date(call.expires_at) < new Date()) throw new GameError('no_call', 'Nobody is waiting on you.');
  if (call.npc_character !== npc.id) throw new GameError('wrong_contact', 'That is not who called you.');
  if (ch.loc !== call.district)
    throw new GameError('district', `They're waiting at ${districtName(call.district)} — travel there first.`, { district: call.district });
  // (Lens D LOW-2) the frozen pay is a CEILING, never an option: goodPriceOf drifts daily and the
  // 24h TTL spans a day boundary, so a held call was a free option on the swing — fulfil only on a
  // day the good runs cheaper than the frozen basis and net > the premium. Re-clamp to the LIVE
  // price × premium at fulfilment: the 15% premium is the deal, whichever day you deliver.
  const live = call.kind === 'freight'
    ? Math.floor(Number(call.qty) * goodPriceOf(call.good_id, call.district) * CONTACTS.CALL_FREIGHT_PREMIUM_BPS / 10000)
    : Infinity;
  const pay = Math.min(Number(call.pay), live, Math.floor(Number(npc.cash)));
  if (pay <= 0) {
    // Robbed blind since the call went out — the request voids, nothing moves. RETURN, never throw
    // (AUDIT-street-life F3): a GameError rolls the whole txn back, which would resurrect the dead
    // call and jam the one-open-call slot until the TTL sweep. The burner precedent — a side-effect
    // that must survive the refusal has to COMMIT, so the refusal can't be a throw.
    await client.query('DELETE FROM contact_calls WHERE character_id=$1', [ch.id]);
    return { ok: true, call: true, voided: true, from: npc.name,
      message: "They got turned over since they called — the job's off." };
  }
  if (call.kind === 'freight') {
    const qty = Number(call.qty);
    const have = Number(h.owned.cargo[call.good_id] || 0);
    if (have < qty) throw new GameError('short', `They want ${qty} ${call.good_id} — you're carrying ${have}.`);
    // the goods change hands — absolute writes both sides (the setCargo discipline, pg-mem INT quirk)
    const mineLeft = have - qty;
    await client.query('DELETE FROM character_cargo WHERE character_id=$1 AND good_id=$2', [ch.id, call.good_id]);
    if (mineLeft > 0) await client.query('INSERT INTO character_cargo (character_id, good_id, qty) VALUES ($1,$2,$3)', [ch.id, call.good_id, mineLeft]);
    h.owned.cargo[call.good_id] = mineLeft;
    const theirs = Number((await client.query(
      'SELECT COALESCE(SUM(qty),0) n FROM character_cargo WHERE character_id=$1 AND good_id=$2', [npc.id, call.good_id])).rows[0].n);
    await client.query('DELETE FROM character_cargo WHERE character_id=$1 AND good_id=$2', [npc.id, call.good_id]);
    await client.query('INSERT INTO character_cargo (character_id, good_id, qty) VALUES ($1,$2,$3)', [npc.id, call.good_id, theirs + qty]);
    if (h.victimOwned?.cargo) h.victimOwned.cargo[call.good_id] = theirs + qty;
  }
  npc.cash = Number(npc.cash) - pay;
  ch.cash = Number(ch.cash) + pay;
  const reason = call.kind === 'freight' ? 'contact:freight' : 'contact:visit';
  await h.ledger(client, { characterId: npc.id, currency: 'cash', amount: -pay, reason, counterparty: ch.id });
  await h.ledger(client, { characterId: ch.id, currency: 'cash', amount: pay, reason, counterparty: npc.id });
  await client.query('DELETE FROM contact_calls WHERE character_id=$1', [ch.id]);
  // the relationship deepens — this is what makes their next call bigger. Absolute-safe: `jobs + 1`
  // is an addition on an INT column, which is the form pg-mem evaluates correctly (only a bound
  // SUBTRACTION sign-flips). Account-keyed, so it survives both parties' deaths like the row does.
  const bumped = await client.query(
    'UPDATE contacts SET jobs = jobs + 1 WHERE owner_account=$1 AND contact_account=$2 RETURNING jobs',
    [ch.account_id, npc.account_id]);
  const jobs = Number(bumped.rows[0]?.jobs || 0);
  await h.track(client, ch.account_id, 'contact_call', { kind: call.kind, pay });
  return { ok: true, call: true, kind: call.kind, from: npc.name, pay,
    jobs, standing: contactStandingOf(jobs).name,
    ...(call.kind === 'freight' ? { good: call.good_id, qty: Number(call.qty) } : {}) };
}

// row hygiene — lapsed requests fade (fulfil already gates on expires_at)
export async function sweepCalls(pool) {
  const r = await pool.query('DELETE FROM contact_calls WHERE expires_at < now()');
  return { swept: r.rowCount || 0 };
}
export { uid as _uid };
